# Generated by Django 5.0.3 on 2024-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Child'), ('Teacher', 'Men')], default='Teacher', max_length=10),
        ),
    ]
