# Generated by Django 5.0.3 on 2024-03-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_subject',
            old_name='user',
            new_name='user_email',
        ),
    ]
