# Generated by Django 5.0.3 on 2024-03-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quize', '0002_rename_user_teacher_subject_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_subject',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
